version: '3.8'

services:
  agents:
    build:
      dockerfile: Dockerfile-apple
      context: ./agents
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src  # Volume for swapagent src

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
    ports:
      - '3333:80'
      
volumes:
  agents_data: